# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yyuan1
# JPush Key configuration
JPUSH_KEY=5107dd2d205db6fbabe57a45
JPUSH_PKGNAME=com.yuewan.yyuan1
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw8rlm2s29v19quc
WX_APP_ID=
ALI_AUTH_KEY=GdKHEtIyP5K2uAKFuXYUaDyjSSd1pxCrJqbLt2JmEIKMpIhaMdlRt1RBjBR/Di30CajHCgLa6U4u7UfO1Z4stQXOoIS95nXLBkcHKKYmDOEuPIAnVKXf4/pMAFbBqxkv8vIrQcOp8xe2B5avtJihX8Z5362wyUsF2P4pDqmmXOd9hfkUd4md2bSJ1xGmcAjS8wYlQ81KKjLcwZO+Na7ej+cPm1Tj18wA7nIVC/dfbMQJ2Mr52NXuTwFpOKizMwPklkoSUAdxnAt52EChgYqgJl1/5XF5W1yTKWLmG4nTabSLE+1ESAA7WA==
MINI_GAME_KEY=ueX0VjmEeFbIVT+zixYgIqxJ3IvTmMxQKPr2536TmTw=
MINI_GAME_SECRET=63c58b753771175e
