# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yyuan2
# JPush Key configuration
JPUSH_KEY=dd4383f61a601e9c83c3ff2e
JPUSH_PKGNAME=com.yuewan.yyuan2
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw8rlm2s29v19quc
WX_APP_ID=
ALI_AUTH_KEY=NTJ4fepgln6wWvZWOL8q9INzkSxszfTHtrNNABNfyZ146MQDzFxxc7Rmc2nqxjgcy617ku7AmMfxLdcebBZP/0+9Ngcj2ZTm2gE682k6Guo5m2KmjxWUPiIEr/RfmoqwXsR/YavDHOzujkEwPe1jK/E4uZMT8XL1L0V1C5detIVLMcQbKEBZjLQKSouRtl+E+fP3K0JhRIi3bLn+8g0DE+FOh1uVdKFmS5RSE/FH4nZRH08cdu55JJeMZzjTDt3sVBuZLMt5Y9dG/YHX62rgXAjCUKoaF3303jSB51L3A17/pSQiToCOSg==
MINI_GAME_KEY=ueX0VjmEeFbIVT+zixYgIkXc8lNyYbfUQfZ26vUHJ8o=
MINI_GAME_SECRET=3cc31f2a7a5fa864
