# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuan8
# JPush Key configuration
JPUSH_KEY=833df27f6857448b71d45e5a
JPUSH_PKGNAME=com.yuewan.yiyuan8
XIAOMI_APPKEY=MI-5511985873742
XIAOMI_APPID=MI-2882303761519858742
MEIZU_APPKEY=MZ-c751cec48c1a45fd9a69d231eace854e
MEIZU_APPID=MZ-140314
# Third-party Key configuration
BYTEDANCE_APP_ID=200605
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=5zv0FpuH1UT3cv0OZTn4AAGJ4HbrHLMNPoDashVsfGrE6PllHdpnK1ZpjU/wJ7ZPmkWH/EjGMHLLtzN+YAGxu5xZ1lapuPOsVCdO8/lfflobZxe4SiNE+4o2nkzPq+vvquRthzc9QuSYcHMSnbY4aTeEDlPBjIr/dDOUIcINIxSuWD12ZqP7EVJeP4Hn/aQOiDw02Zx3581DgaEFs7vmFNF9cov0HwCVmuGQeDciJzSHJeugs/Bfv5vuSxNbIHSJcbIjmfCANs6XnJ9WKFAQOb5z5cqWIZfL1NuDwdk8CehjP87p/sJlUA==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLrsahw//fLu6b8Y2JahXC3s=
MINI_GAME_SECRET=df2a510c3b7473f7
