# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuan9
# JPush Key configuration
JPUSH_KEY=5ec26e255ffd0e4141a9c266
JPUSH_PKGNAME=com.yuewan.yiyuan9
XIAOMI_APPKEY=MI-5841986256334
XIAOMI_APPID=MI-2882303761519862334
MEIZU_APPKEY=MZ-d4a2448f996a40dea7187ad2a09de4fa
MEIZU_APPID=MZ-140393
# Third-party Key configuration
BYTEDANCE_APP_ID=200615
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=I7P8E1rO0rQk51hmPfmRPemOdI1HHlDGv+3MvkvxX6ie8+esF6xUrUbAV9zEMp/HHnh/imihX4PnlhKbqdkirK4LXkMUq9WsHPrEl+apw5bpJ18GM1gE6NeNymcA5g3OkRzCJo+ixCuX1qyAJo+7+lpuYnVEIUas7VqCa7UvarOpEOdCZfIXER+Ndz6qax/wer54ExPHR5iYGfAnrmxdYj3scSojAIzPOP7W27gJewdDpUz0Vra7N9fhkw+3yVI+1goT4s7DYIEbc0d804ESU17wSe6XHUOlpGrNpPkS+dDJMXRqygSBXw==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLp9Q1eFLUyfgciiIEBRDA3g=
MINI_GAME_SECRET=80a7b71d3f9017ef
