# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuana
# JPush Key configuration
JPUSH_KEY=1a325a901eb9327eefb382c1
JPUSH_PKGNAME=com.yuewan.yiyuana
XIAOMI_APPKEY=MI-5991896174378
XIAOMI_APPID=MI-2882303761518961378
MEIZU_APPKEY=MZ-c1cf79987ef94f69b2a0bd5baea72cca
MEIZU_APPID=MZ-140249
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw58f2hfd2695uhi
WX_APP_ID=
ALI_AUTH_KEY=veM9SHZJ30ha1F9+1KsU+DkZGMrxEBw4/xTQ5qxjAG8D8rFXkdcWqmltqpjerzbexBtya/QctYRIY10JCDemlulmdemgj7WxJO9gLxynxzeOzaZKTSlRgJ3V3aJduhpw7q0SbI2/ljNeVbWbdf8CTVk5RzvUMxuUaKcSUpF+NIpCLhgVhkVN1koKJTpXHSTpUFx1fV3zfJHkb6uJFT5JQ1JvP5VTs5qi+eDSFdkdgA4jQDqgnbTW+O/ahpguOFeij9u3L1Yl+pq+209CvQzuzXjdMwpx5UuWBVpGozV00e5PsOOcvA4IBg==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLhwnD6C1oF9U404l4oSlpa8=
MINI_GAME_SECRET=2cc66673f7bedf0c
