# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuanb
# JPush Key configuration
JPUSH_KEY=cea72db7c274dd3c48d28e55
JPUSH_PKGNAME=com.yuewan.yiyuanb
XIAOMI_APPKEY=MI-5171985420414
XIAOMI_APPID=MI-2882303761519854414
MEIZU_APPKEY=MZ-f6a99eea71444792b7d4119b203cf054
MEIZU_APPID=MZ-140266
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw58f2hfd2695uhi
WX_APP_ID=
ALI_AUTH_KEY=sI9d6Hf/EJkKjU2p+YBvduF+BqB7h9soEhF852ZAQRDCciUMrTla5d18z9py8mbNDo29PmAYaoOeyaUxAArSp3lfqi2qTbjHguQls81Ak0ct7Al4FouhEi/Kq8EBqvykOL26cgU7i9j3EtViT0065QknzC/B9VyAXRHvaAgmbJiML0k3dGVhhuWvKUUBSCkC62GHT5Z1WK8FB/MOMRW4O+njkjLPVww/c7oMJ53/htnAzRZI7Cv9WT8ek8N67TWbe5dtoZ3cLNbjxR3hRhgpBbR1qhpFVP8d1lqdxYtMLTURHhPAfT3RxQ==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLrDExiYInMFupE2Ti3+aioE=
MINI_GAME_SECRET=80edccacc77211ad
