# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.youxi.baol
# JPush Key configuration
JPUSH_KEY=d3b3f8c7d912da53e475f3a7
JPUSH_PKGNAME=com.youxi.baol
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=219485
TIKTOK_CLIENT_KEY=aw8rlm2s29v19quc
WX_APP_ID=
ALI_AUTH_KEY=swLbc7YkEjNEP709gYWZI1hBQ+eomCquJIWOmodwLAwNhtyKyV/NC9Mequ5WoI9RLWUHDwcDuUgMCTySMtzAxbnCNfdffQGOSpx+dFaX+AdW0X8iACu/x7nLKHDgSlpCn+7fSxeRnxdS8pmzYzaKeGYhwGcIqAJpAHt8Ez7jNRePwixXk6UQqO0PzAYuQlfW7S/6LsMzcktJ21M1BkCD2I24EW/H7XHJAZY6CImAjUzRKJCgJB93sxZWgufmtHiM4vhUMv8nxbGBgN71XutnCTU/5bhpdCY3eLn2khTz0q8=
MINI_GAME_KEY=Zjqo0S3WnkLrr4TTENskplsZXG9OW6C1FfXSj9X8ltk=
MINI_GAME_SECRET=ab074c049a39c5bc
