# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.youxi.baor
# JPush Key configuration
JPUSH_KEY=31fb64f5b96a0a41f85c664f
JPUSH_PKGNAME=com.youxi.baor
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=219482
TIKTOK_CLIENT_KEY=aw8rlm2s29v19quc
WX_APP_ID=
ALI_AUTH_KEY=zUezgpRO1qyeqkPAWgN0j5GJduy5hS54Y9fbyBdtTC8WBEhwiK7MD2JxHMY5y5KewMcMCHd8688UkOWQec82PLpZaLdXXPHMMvH3MRRxi+bTksDQC+q/JEoqmFLh1FlaxGddCyd5nSwR3JBelLtTB892KZF+wrtJN+uVN1PIr8uLTfP8H+F/1zjeXgE/F2sTXz2PvidDEc9jfnz36GC9YUhEzKQh/R4vRj38xCTEUgXXP/7SiHKxeW36k0vZW6tllelSXoWeL+5ve9l/BXpEHwotX5hXx85kDrv3mwkFxVc=
MINI_GAME_KEY=8e3H8fV7NjAkfgadTdxySFsZXG9OW6C1FfXSj9X8ltk=
MINI_GAME_SECRET=c61de41b119e686a
