# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuanc
# JPush Key configuration
JPUSH_KEY=008ef6adddc091fe62560690
JPUSH_PKGNAME=com.yuewan.yiyuanc
XIAOMI_APPKEY=MI-5261985483422
XIAOMI_APPID=MI-2882303761519854422
MEIZU_APPKEY=MZ-8dec8da62f92447c915c85897b257826
MEIZU_APPID=MZ-140269
# Third-party Key configuration
BYTEDANCE_APP_ID=193687
TIKTOK_CLIENT_KEY=aw58f2hfd2695uhi
WX_APP_ID=
ALI_AUTH_KEY=SaHgRxkEEV2jMmWPS1Q43PAgPmMEy1/n5unK5nmqARMs8N42Csey+r7BDTH2kXN7vmqqoT47BSkhs+8ASlUb3b9bOnDjinRI0uz2qorTO98L054hsWl/6UBLC8jLbtkEas1yOAdtReGfpl6tk4DmZBLlxA7VEUVu/fkdtYKiMRYa34YhXAwstiI7/WodDVUWQy5kTCp9TKf9IHhxF05fzNgl0i7hWGk1y4WITax0TLDVYYggwmDd1CgCen6Mk2uuyGKuDdHHXhUy3eAr+TTdJ1Jl6pWlryd3KDwcKSnb7YYxwiKUm7r2dw==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLhHud2m+8V4qYHVsff0lZjY=
MINI_GAME_SECRET=fee9d6c18990d36b
