# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.chenw
# JPush Key configuration
JPUSH_KEY=3c34766c8b23db649ef2a004
JPUSH_PKGNAME=com.yuewan.chenw
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=219663
TIKTOK_CLIENT_KEY=aw8rlm2s29v19quc
WX_APP_ID=
ALI_AUTH_KEY=ShhQesWBrkQDJw/upB9s3TsiazaiOPfrn8vuTCqRGCgQZsL0CRw6fpCquJlmX3//cbBlxqQmtNUYJX6Qk9O0GWFWr3zySrTRX3nhsQSEecJeqXpkEVP9p0+Zu7nCYLAg7VVYi25uyY03iZN4aSERmpuNkg0onWBr/9dlHYgIqXSdyNYkszwo5GqZ+25V3w2EP+Y3qLYulslKrDZp8L5VBROlB50nMEmrboWa8ZSccDuPDrm0sgKPVpuul3NSUnhsTZtVkd9A7MrFhbhc9rCHdrPgcRpk+F1bP4YF3E6ORYY=
MINI_GAME_KEY=SlqvEhYqmJn15JGjPHilBqpvMQBh42bzRum4ddHlgbQ=
MINI_GAME_SECRET=97977682ea1257c8
