# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuand
# JPush Key configuration
JPUSH_KEY=f66502edf306b5b1f938481c
JPUSH_PKGNAME=com.yuewan.yiyuand
XIAOMI_APPKEY=MI-5931985484426
XIAOMI_APPID=MI-2882303761519854426
MEIZU_APPKEY=MZ-720bdee4faa34911a94697e080a3001c
MEIZU_APPID=MZ-140270
# Third-party Key configuration
BYTEDANCE_APP_ID=193688
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=qNllNelgVSP/jVrjUrxypCxvFhlFKO1W6w7nfXWtKKbAew4rxiQTJUg1pX8YYtxhqapgWUzSB0m+TeejUv6Yxu5BM2z1PJGe4ykvHamrQV9tf/B4G50KdKC8H9ff2MNZyj1+Y/i491SFGyvFWgf5/Qo/+aX02Dmi7505GYtkFeBH4vAhPxm3w+JeyxyF6xJOBSIllDaeVtZD7vPwzgipdpdutBgpv15weI/sfTWn/tHKoQUGDaGTqXME2wsL/FrZNLMrSGtO5jhBWwsYBw2nZR66iS27FKrvMl9dkCRzzgB9UX1N4g+FMA==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLh6ikMAMiWTxUIoAxY7YOAg=
MINI_GAME_SECRET=652531bf49714d48
