# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.danyouxi
# JPush Key configuration
JPUSH_KEY=e678a3c837cc1228efb0d9be
JPUSH_PKGNAME=com.yuewan.danyouxi
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=309526
TIKTOK_CLIENT_KEY=awoxuopqanrqem7k
WX_APP_ID=
ALI_AUTH_KEY=mk5ikOBrE4ddG2R9AEmnuYEDskVdMR3pSnGXWqIIrMIxBTbGS7k9e3kJorYAEObRAGY5xOspo09rdnCJXTGziHmWIWK7+ZJ3ijl6a91f8XLAskoEri4gyEMphfulgXJJbb/9IMhrNvTzg+vjS2hn07AbJfX2j30vY1R2nQotlYI1eF+18lWQQOtkviqxJOHRwEzaTGQOC+zojEuWg6Azi3B4gLI5ohteMwlhJCZFpwAEXZngrhCpliJN3CyqAZY75NfxvI1vVCLuW5ZvySu6CHInIVZ8qsE85u8MGpbLWE9KVDvOgqnFIA==
MINI_GAME_KEY=Po67Wq+oXXZQln3ijPp/l4fGKUp/pm1VxUjNWnWvM2Q=
MINI_GAME_SECRET=df79e0e552fa76cf
