# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuane
# JPush Key configuration
JPUSH_KEY=13b4fe0c22cae389bd8bfcf9
JPUSH_PKGNAME=com.yuewan.yiyuane
XIAOMI_APPKEY=MI-5561985392642
XIAOMI_APPID=MI-2882303761519853642
MEIZU_APPKEY=MZ-b8786616d27e42dba2e4d7b7a8c232d6
MEIZU_APPID=MZ-140250
# Third-party Key configuration
BYTEDANCE_APP_ID=194051
TIKTOK_CLIENT_KEY=awoxuopqanrqem7k
WX_APP_ID=
ALI_AUTH_KEY=+4W3qDsh6CW+6xbCuu0+DstIt/1r7O9HksrLsn+lfxxjSEWnNsSKffzfmrMNCmIi2Is+QIL/CyOP0mq+d5XETy78kFbmg8dMZSXiOzOUt/sgL6JT++k3dgYrovOjz/TXeJbWePNy/9Ln1vhfaMVHEhDCkIYVDEbUhJrWgZ/oaEH/Q6SsiV8V3SqK92uFODJIudynrkRQ17Cbve8TsYemZiCu94DtseB9LH4DKHjfxKO0xz1EcqsNa0x6dkZ2T7tGkAEYXCl6Xl+CU3L/plU77poNTGfi8LiM2ih472mVvh4459qtaWFd2w==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLsQParwXFJpB17awHzLC8iA=
MINI_GAME_SECRET=0d66c9946c74ad1a
