# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.gdt02
# JPush Key configuration
JPUSH_KEY=feb9c8315edca0cf99cfc461
JPUSH_PKGNAME=com.yuewan.gdt02
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=KGczltVP0+GPTWk7RRKyzCPNuQZ20izjlOdOSx8NErWlYFSdD3TizN/WYS3EeHFwFeu1xdcXGFX58T8o3G5X4tx/N0vIyvHF+YkTMv5oCXMG10+NsB+G1h1vTztfYvHqrcLtEwGTegcZ8UVOaPOZ+ZzkDB4AnPg4i2+/+qquvV8A5hXe3O4e/WMKRwAv+qqGvfM8Hiy2KAvzMVVTCDx7yN58Usn2Exk7GXaBh1cYDJN1JC1ERlFy581xWMcDIGdMXJm+G8R/OFnv8CKw/9gY0/RCYlzkQj24Ygce29VqPtA=
MINI_GAME_KEY=PDtxlsgSipacL2lkSbFZgKJAaQo9qi5hukRJHqsVw+Y=
MINI_GAME_SECRET=74117995348ce77f
