# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.gdt03
# JPush Key configuration
JPUSH_KEY=4ff8c804921f57ca400c2275
JPUSH_PKGNAME=com.yuewan.gdt03
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=Db7p2aEr8LXd1leBCyhCg7d5eewbaNbqoiiIBDWXHhhYCULsTkU+J9QLb4sQ35SF/v/VX8/xEzIImkWiFvb4BL7edFD/S62DXdTvI+N2No74Bz6slYyKulRpcykn7N30Bd4VqN1E+fx9iNCoyxIbHYS1j8C4cVxMHFlWoTNbnhVZoQWhVKho8QPsayPdGDGxlMA37G7w50Qz9J9bxjecuz7gwGPvNtTYqimq1MFtbF+6BlL7WgzgnmZtB2aXGd5zWbrkDgZF2lOSKH4mdN/Huxyw0x5sG5ddfQcWgocWyqw=
MINI_GAME_KEY=PDtxlsgSipacL2lkSbFZgDPzu7GmHytSCRRzFtGMvT8=
MINI_GAME_SECRET=7cad6eea9417f179
