# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.gdt01
# JPush Key configuration
JPUSH_KEY=be7faa8b9769a99c4848e854
JPUSH_PKGNAME=com.yuewan.gdt01
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw58f2hfd2695uhi
WX_APP_ID=
ALI_AUTH_KEY=sOS3omQiMwnFlCuufX2IyQr3qDhJKcx7pJ5C/lIhVHK/8Yysk9+jawKfjPjmXTC206Ejl/4No0mK4yqFLWU65I1wusU9sKgjPC52Y2use4+zkVSgqZdD7VNLfSuxp8PhmOhzjQzJjz2uy5yKqhxPR3guC6MZfGvkPFiCVx27kpB/Jb69i6xDbrop/Azjul6i9GbDQnZqf0fnSo3+0umDqqb/dzKv7PanhgaEBY/HVHL7F2wnBRmSBKQyg4yP4FB6UzWUrvKkbdBncsU8m6geZdn0LLptitiP4qZ+YojVfl8=
MINI_GAME_KEY=PDtxlsgSipacL2lkSbFZgJEl0V3fnhLD4IoE4YrQlgY=
MINI_GAME_SECRET=9efc3cecfad9aad0
