# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.guanfang
# JPush Key configuration
JPUSH_KEY=9a3de60094439afa1e0eb90d
JPUSH_PKGNAME=com.yuewan.guanfang
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=207629
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=eI8uQP0828Z8q240KgdGs6+XHC4hkqZ9SqC9kU1fhdst055n9pOY46tizOR3uO6JD7TlH54rddAgy97lYuvfO32QRXTr2wvGmro8JuQPh3PtkXvDHDqBFU5911I012xGCtsjmNl1YQN2MalEYuzfMZiuMkDTFXNtKIRmE+StFFsjCYVpeugwrZcLMQJR89M6BTrT0nfb8STcQCtpmq1Jr9c2E8iqkSp0XcnAHJEkSctKlg/1SvtdQf8Br+V3zSKJ1SU2FF0ju20jAFKaFTZ3ZqEIJQ+BhSCZGum4Xv4Apnqb9WMRR5rdfw==
MINI_GAME_KEY=twJCGm8UmP4ESkx0ThlpC+Kgb0Igq5WkSXIB6bfcyrQ=
MINI_GAME_SECRET=3e9dc86e6f41d9f4
