# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.hongbao
# JPush Key configuration
JPUSH_KEY=fdb8ae41f68d1300c726fb11
JPUSH_PKGNAME=com.yuewan.hongbao
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=207628
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=DJZrQkJg+gRsrvqc8ejHagx8av7l0qHouCC0cc4vhsS7oHEJCWbUireorsPvgWa8OhWT4g+G5VlXqU5r5RJIKroHoyaaqDtdjFgoh0vot1mlNjENtpfztImM3dz8guNN52EpFX99dKdUgd9uXvgpjYDs7xMCwGjm2f6wyYwJbihS+0OmI7V6hw+LXqLAp7EzockSajUlg58HWco0tgUIcC+2dmFkWnuO1J0K02FityNVZpPKZnHw+bOvc7fx0f70jazpXdvWw+Bh/Vd+dyLqo+TdZFFNdxGQIXFG4Ka9M42d/1NsNOvUog==
MINI_GAME_KEY=4Z3Nr0lloSppK8htskkoZv+hDLlpFsSoxqMOj5idXbk=
MINI_GAME_SECRET=32d9827117c05c84
