# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.youxi.huojian
# JPush Key configuration
JPUSH_KEY=5950e8a33d7a451b81571952
JPUSH_PKGNAME=com.youxi.huojian
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=214608
TIKTOK_CLIENT_KEY=aw8rlm2s29v19quc
WX_APP_ID=
ALI_AUTH_KEY=M7SpBvz5rrbJWI4ZWoibvw1vGWAsCd9h30mXjTTxdY4jbk8aiDrwRT9Z3O2R0KI9EeyLUM3DkLIUwpBKSN8Arelh/6RjifgB0WLgZoSoCc4r65oEzibS6ZEGIFomnuPACSgMwJIv6NaeRqmukzRMHkgMI9Q7r1GQde9MqKG92y5OHw9jCIXWbDJMbgDeVdsXubfuAUlrPFS8FL4eeBFaSBcqVmwWLGgNpedp5WRi0PNTgozv4a/SUVGpGn8qPJShLVVrEoPE7CbcswCYbHM2Ij0LbFpAv8WHeamvtqxV+UtVRwz3FlrXdg==
MINI_GAME_KEY=NkX09vepzmyq7BhcJR0V3ZIxQCp/ZyIY6Ibmahbl8WQ=
MINI_GAME_SECRET=810818c502b8458e
