# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yynhyd
# JPush Key configuration
JPUSH_KEY=f782f4da767d076d2abc1c45
JPUSH_PKGNAME=com.yuewan.yynhyd
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=239695
TIKTOK_CLIENT_KEY=awoxuopqanrqem7k
WX_APP_ID=
ALI_AUTH_KEY=V1uAePp1GkNiZXzdZ2ledVW6Ex1CJwkKiLDjvMiMJ8i22QQTuUl3tlpk77A0zLY7fwdI2zK2Cp4wcMcNiZaRgIAR7LtLasDA9JqikqY1+FSdqfn2zfATb11+a0FZC9nVarHDvKzp9aWi6hyRE2GImyRegEL3hu63JxYiqvLDTOO8TtY0vTEWNc0wKNlfJ6NYYOZGEd37HKU8hogS/kkL9dUFkDzuqaogq0NYcSFabkXPZQ2fK1i13uXzKbLxUPMHprqLE8pivd12o7p9Fag//ontOs2ojvgISsmgQS3I3ufFCFgBiJ6TgA==
MINI_GAME_KEY=0uBkaOVv/D0rQuzTy5r/RW2ya/1uIfzbFs7g5siDaw8=
MINI_GAME_SECRET=2d13367512bb914a
