# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.shengji
# JPush Key configuration
JPUSH_KEY=d86a57056832ad4d794a3687
JPUSH_PKGNAME=com.yuewan.shengji
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=207630
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=RFltCKix5Uz0AI1B9pF3mO7QAWD/keTXNQzEOZxhcyRnX0loxx95ARLI9qQunbelTEqzDOqhYgcZubr90xkd9Oa8RqAA4U16haJS6m/nGhwcYXqCXdseQpk+Wl6pbVTwhYc8JYsQ/z2hd46F2uhS4UP/Gc7jfueNpCBjViLgHa9C9UYmM/2E6+3hiRNSSLWEemOVsJA5UERDETSuhQTPQ6emGWhU/eotCDrWrg8iZDMRJGoxq5OgUnu0XiFdZmHfjqwI/Ld08glJJGisTEjMtFNe69cMPne9A/XrcUQxJxMByOXAvP0cvw==
MINI_GAME_KEY=EpJKe6ooDZEeA6+UjLciZb7LJqX5oVIrh/JdP5RvWRw=
MINI_GAME_SECRET=dc0775bc8bcfcc61
