# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.toutiaosousuo
# JPush Key configuration
JPUSH_KEY=d16dd38b2735b4cf80f49f5f
JPUSH_PKGNAME=com.yuewan.toutiaosousuo
XIAOMI_APPKEY=MI-5921986219344
XIAOMI_APPID=MI-2882303761519862344
MEIZU_APPKEY=MZ-865cf2f7d8034b569095b1fcc8e6e4a5
MEIZU_APPID=MZ-140397
# Third-party Key configuration
BYTEDANCE_APP_ID=207003
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=JZZDzPN3lUZ/RzfYkOJOm5AJi2YxPLSYqNGgIg/OzezVtK1nanqrVMsFgi7W5nTpwCs5BNzjYUHvekHc8vtBtEk/A5KaLJWnxYVo1eQBLb3OF25/zxuKaieC6EcI4KaZfv6naKpvCP8MFoQsjDlh6u+yhzUmMou2i+0pr7YA2HrKrVhcmQC/GcR0NoTgfeVxSIC43tpmzB0cfcOXxk5RNAGL56UTHFQM4DghOVA5vY4vUus9SvUQMrbnlzCJ1YttVFDeOtlquINoi7Y2nqLiLStZoqFq2+q3G4EgwiCKOFM4Keafa+HKpw==
MINI_GAME_KEY=NaWOdxSYGVZsAOKoBPpe84yJdzRjlBi/RX3dRdw2nK9ndG2JOPsS9yA5fww36gSp
MINI_GAME_SECRET=69b7aff23e71b7fc
