# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.tt01
# JPush Key configuration
JPUSH_KEY=91510c3904ce7c70c00635cb
JPUSH_PKGNAME=com.yuewan.tt01
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=O3DMMJn4P7ht/boouuXkLgjPQSe0mwokcg7D5cMoqwYdwV1l+PKwYAonb8CCtXgvpZ3BDkeDQ/2NGMsAJZwkXcEj15MX33RYBEmBQC0vzarbv/PtBYJ2eCsqFOmSz5v0+6htK3rVJAaCvi5Ct+mXPQshHF1gyXRaAnvKaei8vFjleJlQfzavK/ClqeBb/eU/KXKmqJ8tmSUtHtTEtBNl9XiJn+y+NJdx9QiH/RL2TovGX75zATi2tQi4PU53+IjoKX+e/+809GcONJNKpA04R1P2UUBPE/+E9sGHNXnIUhs=
MINI_GAME_KEY=x+pcWNr6IQtpS6P34CKFoTBLbznciVRW5s3WeZM3An4=
MINI_GAME_SECRET=c55db5f5ea629ff9
