# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.wangchengzhengba
# JPush Key configuration
JPUSH_KEY=fdd2f8139fb94f6855e8add7
JPUSH_PKGNAME=com.yuewan.wangchengzhengba
XIAOMI_APPKEY=MI-5471986240340
XIAOMI_APPID=MI-2882303761519862340
MEIZU_APPKEY=MZ-125865c6ea06489ba7c8831d46aa7101
MEIZU_APPID=MZ-140396
# Third-party Key configuration
BYTEDANCE_APP_ID=201174
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=TBoBNZ1texaNtAFUXmWSEp7uCf/SUFVhoWwonLcG1GgP71u6NZqWfyL1Okgp6SxHUsvR3tkxjlTmHU3IHVws8EaeD6c1T8vfxlNEc5rOel+1KByYqxpjvCeK7+dFzvq/va5NU/kUnEM3sa+bIDbEZwWXc1Woq9BYLYMN9u4jCW8ZWJ2DZ0j8rVKiUuX64sVyVZpbPBauIQlDvfi5CQ+16658Km7/nkTMOS13fdoQkF9qTMkQWmZFjZztm4Y0gr9E3K2k3TacX/j6GcWuJAC92Z7YCJomRY1k8+YDsMw/fAoMcy47rtgIRNNv9SocSZWJ
MINI_GAME_KEY=rOg+p73XUPu7pePA1VCcaBqveVd4NXrGhVz3NRAsPKDNPMAekIGEZphE8FgsSx+V
MINI_GAME_SECRET=ae726db3d8a5c670
