# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.xcxttyz
# JPush Key configuration
JPUSH_KEY=3bf7a6bc68236f52e58b780c
JPUSH_PKGNAME=com.yuewan.xcxttyz
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=D97esntpEwcC1yvr38Znsgu/JIhRpxiNuT2NNgIs12Gp9o6GqnGtP14Z9aQaHd8BNWZGak7mMe5hWc4vj60J2XcOudd/koqRrAM2cb9Kj7gFtGWvpybMF/fjivXVsr0zk+//WquKrI9iGix4bl9EydX+5vGAOxwySSHGZxGBPXShIiOr0EAUgH02VQJtJWzwudxssXEIXTwqiu5eDZI+RkhnVwIxEHb76ii8L9t2Ho5O10l+CiBLal7wnd0sgYSH6rzm4A2x/xVjW6lkTLumhF2uDAi77OZnQPl/JdTzms2WuRQjOV8wmA==
MINI_GAME_KEY=RQU4boyO40NbpqtmWu2ZS7InJ60ql353tFVohFWxTRo=
MINI_GAME_SECRET=7614f729f2496cf0
