# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.xiaokun
# JPush Key configuration
JPUSH_KEY=f6d087a9be7439b3504a8588
JPUSH_PKGNAME=com.yuewan.xiaokun
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=211028
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=fOQzPfmCMlxGddwDfoXT9sBeHA7oZNf7tq1kwy/ewP/HWeSD/e1yHyOpOJY0YpCFsz7E+E36d9RWwwPTGiMGfl8pv2E+0BWS31Shy9HGMdrrGbnMDtetjyGQ5/5xgGQp/zwXLW02MxR0GyS3BM+7s+SMrqLYwPx0D+15DYjOe4nGcjWWh+NM2FlmrULBpvoSkpVA+V54bFTB274w2XzEv8SGJKr+BIJ4UOee9UMIVbSkoLhKd+4i5Zh7JRFJI85TZXNIuMGn0T7TpVNVAT0GvW0JhxuKOGauRNS3NRNqTxCZWgJK62Odhw==
MINI_GAME_KEY=K9IUJY7xU2baU9hUR8fh9omREAH1C14lGU5gpS32IkY=
MINI_GAME_SECRET=a7ba503737bd4c6a
