# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.youxi.xiaoba
# JPush Key configuration
JPUSH_KEY=2c42486a181144973de2b197
JPUSH_PKGNAME=com.youxi.xiaoba
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=214584
TIKTOK_CLIENT_KEY=aw8rlm2s29v19quc
WX_APP_ID=
ALI_AUTH_KEY=N7Qc2NXHuGyOkSadidjWDlnU3pByaCMlcNb+OcOGDEsBzRxxeHQ33uPCE+FhhiuoRnsghyyNSYqmkuVlWCnwg1dDd+71joAqRbd6m4bO3QAYigcGO2Ej6pq1OKMELtFtCkwaGZufhjtTY6e9ObYQMjgje6asKf8hxouFJ9Yzp5sCgCXx68NEKh6dcnAcApMtrwaotv1q2vyEgMVfoTEY+QjtskqQ/W/rAZhJ3Di2vNvphYBZngeS4rYV0CJuSS1JJOYkxXMg5btgqFICE4hUEq0ELx3ggUXpseejw9TkS4g=
MINI_GAME_KEY=f/AQwh16RdUbJooq1AK4aCZx/R9RNUMdCaRPqli11uE=
MINI_GAME_SECRET=3810d05bdf0db4d8
