# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.xinyu
# JPush Key configuration
JPUSH_KEY=eb527c28db265f662547bd39
JPUSH_PKGNAME=com.yuewan.xinyu
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=211030
TIKTOK_CLIENT_KEY=aw8rlm2s29v19quc
WX_APP_ID=
ALI_AUTH_KEY=7RMPoPJZlODj8y46nu4lCKktA36hbkNNht0/+3dmLGWDY7n6R0xZb82UQaigmUcyTj34qUbGsfOOZyOUxFtYK3JolL/7nIBf6A7SGvrYeJHSLx0KA32M6Spy6gk4o98zUWjm7soBZWZhgVN+vMThmIJFV8W0Tn7d8874FF4O2JDR2qGv1oztBDOyuz7EzOgRqN7EiN8ogweGLNKFsKv6/EjCU5TNYCa+KXAG0evjnZoqx5aOqiODexnJABEY8xEwf8ZGXuNcGENN6g+cYXbCQOxNs+rvP3J9bnF8/E+uXUY=
MINI_GAME_KEY=J9fBndKEXlghxnDN4G/alxhfQZnz/RKVX6u6QTruYOs=
MINI_GAME_SECRET=d5d9d67f1b5253b6
