# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuandyyz04
# JPush Key configuration
JPUSH_KEY=71c10bc01e60eb0d276eb2bf
JPUSH_PKGNAME=com.yuewan.yiyuandyyz04
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=RHXzsfHv0MIwbyHJ8lTICtVdknjg1EyFwBC9zVFL1VLp9Zz5WSnNXX7LE8ongYN1B+O2a5XzBGnqrzx5vnALNo8f/XPQuy85g/lxnXoX0dxmESjQCzQgEiTzvRWOQnoegWmpM2r6jiIFxXClQfbI4VvY2bekIll9Pjp7gB5NJQo1ZKA8MG74DOEznYAL2EfJpHgo1Cwfc9NrzzkDu6o+bXeVCYzmCCjQtxqCU6mm1bEj9Q0fdsFkAR2viqfRaM4G2k0h31cxzL9RX5N4MjAxNThjQ1kRS/cemJNoSixXiVWDh8DeRAFJqw==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLo7q/kZmlEA5PtaxFABdnCXXMUZS9co7NSiJgdEUxGIu
MINI_GAME_SECRET=f68cb506a567c3f9
