# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuanuc
# JPush Key configuration
JPUSH_KEY=5f04f574c548353737780074
JPUSH_PKGNAME=com.yuewan.yiyuanuc
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw58f2hfd2695uhi
WX_APP_ID=
ALI_AUTH_KEY=/HYl5drwKZBrNjhxThmfCmcE87gNVk9j9N23eW4p+520eWNOLJ2VZ11OViYKIFeEpo32eZTtwCmngzVcs9IUIWLJnpif78FYz+iZl0wnlqief8YjIYNBSpivsULlEk+4+6bKkdzGAVbbNwJ6ETXv6XARR3cA7RBTmLCN/vcgbleBCq5o0udsnhu5DyH51jIa334CfIOrnPfTeJiRGreViUpJGlOHv27R/x+iu+v6Pzn7QM91z2qcT6AZrec8Ncbwlp9IL1mxIOLEcXhooqQDicEBmNQA4glw3o9s0UwEi+K0yWRu3LUgyg==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLipZZjUxSvriFQ4hdsAS9Hs=
MINI_GAME_SECRET=4fd906957c0bd85b
