# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuangdtyz01
# JPush Key configuration
JPUSH_KEY=a61d458b727efc0b29a74fe9
JPUSH_PKGNAME=com.yuewan.yiyuangdtyz01
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=Lwto8029rRPY7qWUxMQOMtFpk48UWgC4fpe46dPzGEQ6LSzpOliPuX8H891AxCrtdISVZjK6lYf5idLweCESCgBMIE1W3NpW1RESv3lSUBFkshG5d+eHrJzHsSWyLiNa1TeKiaZtaJFMcHMV5nZpWk9TQZbFCDoeTPWpP3b8CIm1uOIuNzk1vWK4jBXBAdswApuNLOIvI74DBAOouUOUMm8WN2CO2VeI+E1rA2Wyiwu4IwyvWHm1cYhvb6reO58fT16mWeFJv/C1BRGtf7GWXgonP5JLXlXymL4hcGm57AETIexJhLt0SA==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLsccJuJ8ZdERAy3jMvCX3J+akNFLQCezdlq9WCDBjFHk
MINI_GAME_SECRET=ef2d3c770311c88d
