# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuanapi01
# JPush Key configuration
JPUSH_KEY=416409e3d81910b9f53847c2
JPUSH_PKGNAME=com.yuewan.yiyuanapi01
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw58f2hfd2695uhi
WX_APP_ID=
ALI_AUTH_KEY=xX+2ntnclMIpOhY9ISocoOYc+vZsHjYki9bPiXM8D52EQ3JhDo8WAxXurfA5eH9m9jb2VbGJm0Dsl0h9HKHLcOODZjELnHO0g1iyqPzfLgXZU2trfdTRe2x10pYok1xPlC8A3W4++ia1IiEU2CBScFSIyplIS15v/EXQB3tdEzoSG8KPyJOxx7h61WR2/GIhKu9WeOoo6xTZPaKB+vzTcHlXl3BpYEBzLeEOZb0BJ5cFY3HqXiGjFuCY752mDFj/m6SDYjXBy2MKh3LVnlxMzmJmcGul36RT+v7qNv9YkwzPRBr44urYWw==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLsyPgdza62nFQg4svoV/+gSgA4x+JWh7hhNS5aO52BFs
MINI_GAME_SECRET=9e7e42b48f1aea38
