# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuandy
# JPush Key configuration
JPUSH_KEY=bb48eebd18723ee24a70f968
JPUSH_PKGNAME=com.yuewan.yiyuandy
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=310621
TIKTOK_CLIENT_KEY=awoxuopqanrqem7k
WX_APP_ID=
ALI_AUTH_KEY=JXdqW7CQUxKrc2JIWxStWW5bBYzKyRl1jos/+buIpsDd3AFKWzjmViLSrdWogqk/Osiau8Dd7suyQUA3VJ2611nDDyg3QWg93av/goFCAW1jwzp9ZXJOueKQq1GLm4k4Re1mvgT5P/1PermC30/lcMu+wUMbHSG5IjpgPyB0cqRrPSbHUqTWVV0dYJNoTK+Iav4HNM5Q8DMRB7uXwCqB3hplJIJ1LPjXtSqmYZt2k5mn+wDQ3wClILaxlqDUDq/+xaoM/w9dOnFQx0xWRBuBRnlzMC0zv0CC8yoDPvjoqLMjG6LDFuKJWA==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLs+8oiV/sfURBgPlit5oCj8=
MINI_GAME_SECRET=f4ac773a236d656f
