# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuangksyz
# JPush Key configuration
JPUSH_KEY=1bb380bb80de6604750c3a7f
JPUSH_PKGNAME=com.yuewan.yiyuangksyz
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=EpmqP9wKF2zwctrnHxGGUWvs7KMPYGphp5t1uJLrmC8snDRwDKZ43RZtO/PsmlJ9IGQtjqau87oOVFKtG6Ju+8SPhIMF0DJcYR0zVCSvQiJYLOB6TAZmO8p2rzMnfF2JWycngjwvjAPjIVAoI5gwwx5ogrROKnVSh+D0YPU0XDnQrDLpKmpNBqoPtmeiAVKvlR9vEjbpEYA08dG2mUl3xW3WB1ABFYA+IXlnQHSoHrDSOeAyBUDBUqhVbSELmkTLiUMjO0topA46JW58JSjVsbkQqu0xRytBc8g6z87TCS1PaSWI3evHBQ==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLtVYnUFEbI6GII93m2qAmAygA4x+JWh7hhNS5aO52BFs
MINI_GAME_SECRET=1370b90f684413f3
