# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuandyyz06
# JPush Key configuration
JPUSH_KEY=2938f06b51720b6fb298370e
JPUSH_PKGNAME=com.yuewan.yiyuandyyz06
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=MmtNpUoiddQLJcGgV1u9XBzdnvum6KN5V6b/4gz9f31gGfYHnbujYEWe3oF0XQ1sFl7XQTJLlE/A2MSLe+X2A58aWZ8cJQ5eX7AvknAZzm1RUGRvPj4LiOjxDR0xNkQcMGU7L7psg2mxH/FeQbzauVIvN/lmmLW6SjgnpiNiE8u1L4vvAU+cZxo+91YbVqA5FmtRRW0w6Vn5c3kzBmdbbSp1lsJGlMxwUv5ZRNmYDMou97BrExK3wbJ5yZcCTKUbs+8ZHJnzUJt3mXgPb3DyMlUzhgSjb8twjBu2lO8WC24dKGfcBSRDJA==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLrb4UPJS81l24kTdD0ydeOzXMUZS9co7NSiJgdEUxGIu
MINI_GAME_SECRET=712d9b2519a17d89
