# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuansg
# JPush Key configuration
JPUSH_KEY=beddfdc9b29b291585c3fc6c
JPUSH_PKGNAME=com.yuewan.yiyuansg
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw58f2hfd2695uhi
WX_APP_ID=
ALI_AUTH_KEY=iQNoiNzmkm3HLGTVmclAy9/zhKe2QzVkezV2RIQWAwF0G2RTnN7EEktJM+PfCbq0ea8ak4zPtGxHuXwxJIE9X7EaZ7RvTRFZ8/AhUYziiLFllS5/c9roQFaYs4ve03eQPlOvtayeZDgnwGAejIBjigUqLp+JxigLgJytWTcs5gfnCKfeofRoVc5waEyirrgfUcA0QWSkDqaxqmWZRLQSMnYM9lObMamdbxazDa7fzSOgKTu2HfDdUf9cuW8N6WVOhWCqjgPijXPNdhvteQBTQzKOM+qehV/Bxk1OgpYwto7lIyJzwFtfyA==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLq0PbEkJvZaK7KBMIknGkuc=
MINI_GAME_SECRET=69e5152be26a507a
