# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuandyyz07
# JPush Key configuration
JPUSH_KEY=c62122e829109e3777ba795c
JPUSH_PKGNAME=com.yuewan.yiyuandyyz07
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=PqBVi+l3D8GwMFMNfiwGwlbIoCC7zKaex6PeVjIcjWvP+3Blf4hRfVzW3emjbF5JMsyHVVEpRw8NX1aSHIjbqQuzRMhjOeIRsYcFblt+x/j+61nBZWOLnbFawRk/P9xXlhDipaf4NCkSuKspCe0/VibOsqzDSj2AijcdpOxxVIIREtyuWM/K+kJJC2W7dOpMwwQhDJY/jPEu5dQpL2yPgNiKkmBq1WIxtjLE/kaanun7G0wSqJX9cLDy490jUQN/xFaQSKtTAsXF4cr8qh1uLlOzV021yeBm0DWlIeWqaPMDK8UnculVJA==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLoIVHuhpHJZbc447BB0YUirXMUZS9co7NSiJgdEUxGIu
MINI_GAME_SECRET=93c2302663a5ed2d
