# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuandyyz05
# JPush Key configuration
JPUSH_KEY=2f32de82c6d67782c77b7be3
JPUSH_PKGNAME=com.yuewan.yiyuandyyz05
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=ZrQbUl3prG4cq9E+9+agnUu2BD2kz6+6dsBrCrCN+f/MyH3uhsLoHMeu/oVxoFySb72y5IIEdNydF4T6pP0ZeZjtOGrCbEt2lUE9qNQq++VVt0vZbESiAoNZ2BCaZnN+VRMLsfYPzdY8MXbN7IHuM9TmhDZXWjBCObaYFXqg1RjlpfXG3CGg43caK9CnW8lbkOrTKLrIarVncEMT6T6hQ3L1mEGCM2RcEb6XmuKSqadnDIwUm7vYzy0mDN/K54as2D/o5Hvnbimmu6W8UkvG4f8mwZlm5TONhkp9HK5CL/RSdKtSEQKJgw==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLhjq060OpNVm92o+jp68zCLXMUZS9co7NSiJgdEUxGIu
MINI_GAME_SECRET=8eb6e943b693832c
