# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yxfbd
# JPush Key configuration
JPUSH_KEY=18d84cec4a0cf51022e52922
JPUSH_PKGNAME=com.yuewan.yxfbd
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=QROECua6n9Z3dhJUIOAyt7kK332E7GGqL+lImp6kQqfNSDe4wnoP54dbLRjPszyyUHj2giYWMzuwLz1YD8IAn1eDynIeYGETpW3HPQT+/oXQZDoT6pXWaC+sdoZbIR3cCOgY/qLXBQHUgSsVUeUz2MneKER849l9QMWY9/nijTLubrQo9MLUgeifmupolcemILBs7exIwJtbGeZtCmCP22avLemtdAsuKOWmyhj9T8qrLl7Ukt4Fv2mOZ4iimSfqE8OyNR/Dg9xAM/5aG9TD669p52UasW4xENW/3IuhEic=
MINI_GAME_KEY=MVAoIFw1qYsNArOpWc12CjJicvl5KJhrrJ75h5dBgrg=
MINI_GAME_SECRET=f50090723baa808a
