# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuanksyz01
# JPush Key configuration
JPUSH_KEY=62bbc673782c843931c62f72
JPUSH_PKGNAME=com.yuewan.yiyuanksyz01
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=7F5xZppcAEfaC5v/A2tIQXfCD2K4ZE3kXJYQBUc0ILK9y4Difh3/TeswU2ju1WxJzvIB6+ZjD42hMw+Jyy/5o/dl05kcAz72LFnnqpWO8vttWcoN14fkvJYiX/1Jk0Vdw/8CboPa72fdb4W/bPXRTapeN3ZVh56BXRivCYdzj06hmWyy9psg3oLsjSaR/FqgGYUPlU9m4UQHFsVpqlgRcXktxJrK9b6nPiGnX4pHx/QkPNuj/zvGAAuTuAwSlCZ1Kel0jvXVjmahe5wEu+hlPRNRZez6t1GBbxKwzhtWD+m7KAzNJVfd0w==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLpIU3DQVwai1sAVi8HKa6jnKd7Li02DdQcJ9Ov9AJZYn
MINI_GAME_SECRET=7d58720fb699801c
