# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuangdt
# JPush Key configuration
JPUSH_KEY=fe857a2936d903fa793921d7
JPUSH_PKGNAME=com.yuewan.yiyuangdt
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=awoxuopqanrqem7k
WX_APP_ID=
ALI_AUTH_KEY=NBeswGgeIwoYcl5dlBoXTNkKdkJaUEXuc32TTJ7H9PsvvQKR+Lrx2vJxp1ob70wEU6hR3wvI8DXx4sfRur/SWzDFnfUpRHtX2ZUniOPm7Iq9YCvCcUffBnBUC7F8X/e+Ocf2CMxmnB+yLLGnLb/Txgo3pN26Z7cxKXPuH4FI9NM1olInSWtjj1by0q152HPwnrDoRAB5kBW5al9HMkXWd+njUxyJwoJUw+nk8f9R4oCWcIQcF/Q7F/YwheOptk+oYVMvfdUScoxU4qHDPA96pWp81X7VozEDOvKJ+oQF+cYzmYBmJ5sLYA==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLncI8mGrHjN+g9VOGiWD+EM=
MINI_GAME_SECRET=795df20c946dfddf
