# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuanyz02
# JPush Key configuration
JPUSH_KEY=5a067800dd57a563e8e414a2
JPUSH_PKGNAME=com.yuewan.yiyuanyz02
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=LQsE7D4/p8xYRS9PIqIGRoS6FOsVYr7C73zxJ/ubplLmHopfJQGTwPQiOpOR46jWXxwpMGkIMSelsSLA5UGq75B74PkDD/wNWaODkq1FuNpTXaVkaFfCqKFpbSQdZRbhVg+R0brDBlpEG1Uzi7mw+pYBgBszOyGF60C0GTvKd7VlSPLiR+9wrULQK9XkjgN5jFjfLtCiEyzB7nOxK50OZpdrSwF2DRX0K8CDF4cX5gtDaQcBVV92UrJqtCzGf3KEQv6IA1RjcFVh4l7LogV+7j09rLpMKorwl16GXxJW9KUx7ke8H3ZBlg==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLg+0Id8irMx4UOp2aRt7jI0=
MINI_GAME_SECRET=b55af077dede75d7
