# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuangbdyz
# JPush Key configuration
JPUSH_KEY=3280271ea769d117e813e25b
JPUSH_PKGNAME=com.yuewan.yiyuangbdyz
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=OPGwHy4hADhsiHm3HzlOxP3J1kJdv28C9Z1Cpr2oG7z0XHYUIRUVNOlYTM5wLkZzGHoGpzijNINWY2Cnu59SVBGtGZY4Hfqhi/H8Ch2eCZUEradXHg+RqbU6/DtjNRo47FKcRJPEKyAVCv8a+E5cUySDPrICwwJWAlqayCBxaorEVJAeo21zVdMBnHGifHt9EouTsFCC071ozqAQbopTZJ2vTlElwiLlmLCCPlITdhx5ubTugE68xhcanyfC7a5zcOALXlgsMwQDQEebdyjAVJc4/4pNR3s5yuUidDe1jjSO+Bi87Ew/wQ==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLjx5T/DPCQyazukXkI28VqSgA4x+JWh7hhNS5aO52BFs
MINI_GAME_SECRET=28d8d611137ce8c4
