# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuangdtyz
# JPush Key configuration
JPUSH_KEY=f7b5934888c5d67fcffa5254
JPUSH_PKGNAME=com.yuewan.yiyuangdtyz
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=7+Yk38nFL0wqFXbmZyKwl5TIjgRUWaoMIITgJD22BPwKMa37tGF+6YczivaMFz4NdRidkbjaZhpY8Hopp1vI2iWsUuulCfBnI/TyHRUzCcZP3nePlIB2vzy7mBvVbPQm3Ra7E03N/9ZY58zC5kOom+D33UkUKZ0Uk3lACEVVtVEOs+BdOpE7SQKkInHfRogPs+LquAG6WBNZGSYZWSCOawzkjQsM/mX0mst/9kHdRF8yNlOxckPcK8bMVbrPlcUVvpGdIrnXj+utOcBvDrV8Ren6oxCZtidbUJPq1m4TDCV7H+pOzEKt5Q==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLucsrX5fk97psTimtd5F4/KgA4x+JWh7hhNS5aO52BFs
MINI_GAME_SECRET=89362c77754ae04a
