# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuanksyz02
# JPush Key configuration
JPUSH_KEY=3f4f28f1a671a1e8a9a81dde
JPUSH_PKGNAME=com.yuewan.yiyuanksyz02
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=YSGL5jxOskllwfaCzOYNAAjgGFlvMr+wdgIFYPTbOSXNMK8XcurjH16sFegai2HoLClAUlYwnVhT+6n4Ss1BgyJrs9gLGtPQ7HlgK0XZnjen13hciUx4LUSjSC3WNw97KXer+draQ4jsaS896ZKcAflCHBcVQsat1kZdWz5IEdQgyxzM2dcJfkurbMperhfRVMLfOkwghpPF3GdyWuNK99liq5nz2966UChicxUSDvjt9ECI2171w3G63Sold2vCroGIIxbjzSYI1QQ9sGWsJpRk/lvz0skn535A5cn1m13F3LbH42GHGw==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLlte1pnSSWIoP1wTPZLDWFTKd7Li02DdQcJ9Ov9AJZYn
MINI_GAME_SECRET=3a37539f0e0571cc
