# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuanyz
# JPush Key configuration
JPUSH_KEY=c6ecf0f81a3cbe4a376009cb
JPUSH_PKGNAME=com.yuewan.yiyuanyz
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=bfvqrjRsmP9/xD22Pi3JCiPBa9+B2TxYzOHkWTU4yqqfhIH70e4uiYCdzVbzZVx/hg13utQwPpPquuvhY35z9XmZOya0ZPz7gU9OChMbpmGVrdczudBLX3Us+hb18cA3Z7fk9kYsDOwDXfLuWxLg+X1su6RDeyD6QaX0uCg3Lnu2nAqPvhJYRMEFgSxf7nE96pakKhUHPKgVqa+awsrM8WIxYRC/KCiEpX2VCT+Rhkd0aa+vmYgGB3USLCOlyMXfT7Rr09giLzKlyZRY50ZO83Bm0PRX5Q2hMLMh4hZvjjXDd9KpEE7Z0A==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLgQI1b1H7T2McIkJjYELJkg=
MINI_GAME_SECRET=737b590a97b38187
