# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.youyidy
# JPush Key configuration
JPUSH_KEY=e04d56a4b139cf40abf29307
JPUSH_PKGNAME=com.yuewan.youyidy
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=335722
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=KqJWwvbozDZkHuARIUHtPY3yARoZBYhzvKzTdALcZ6Z24eU9r7K/zjVNzX/cPIcbZZHYuVzDvDMI1BdU3YbV0nszS+f5wrYDd7ckydEu/+kjd/vVi85bAEvyajP20WEXWdViicpPPWUMwdQ1fWjYNhYXKVaZ3X6Vr69Vv4lKQlK1w7UveMGya/CJ3PDrEx1n7ecVHCaD+w2dvOyNKKmwhPWFmmJMavMBqcf7jnWU0D/MXw8lwRjFRrxzBShgNM55S6d2hyDsksvlYjv0QyrfGhNr0ZuUS50H+TOnUSDUF33CALBqpANPAg==
MINI_GAME_KEY=4kJEs2HTkviAB38Q+EuIlQuyCC5M2eyp+1aZ9ESoRLM=
MINI_GAME_SECRET=0f0cc8739c8d37b2
