# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yyhezidanyou
# JPush Key configuration
JPUSH_KEY=3bb2ce5e6c15ac2864cd355b
JPUSH_PKGNAME=com.yuewan.yyhezidanyou
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=305523
TIKTOK_CLIENT_KEY=awoxuopqanrqem7k
WX_APP_ID=
ALI_AUTH_KEY=u6MOSd9qddUntQS1Iv2vIsYaKze+t+X8kDjYAZF+VNvm0/sZwc+btEbZxetbcXsvZ6f2sARSHETVcoLBbtKrgR87tnlfjWB3knXCu1NvOQCwknK8IFSXF0iXPlDUXy1CUt7pTtaFjNquqM4hgRPbSBkTI3BzKuVOpbUDUYxyK0S4qP8kaEcLxNqhI1/94aAOjILPBdDUXENgi/urDvxjzc1NlwrJIY/V41HvkaTyxBqrCqsNTtd0iJweE2FHaKOduDiVo8DfHqD+3tBUokeaJCuUde+l2uIamZ4nj3Jv6CPsX330QW4r4w==
MINI_GAME_KEY=qplHRNOJxyciGt7xzGMMYiW4QOQpa6+NcLyy+taLw0jKd7Li02DdQcJ9Ov9AJZYn
MINI_GAME_SECRET=66c424f1394cd5ff
