# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yysytt
# JPush Key configuration
JPUSH_KEY=86048eee4b5dd0dcc5845fcd
JPUSH_PKGNAME=com.yuewan.yysytt
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=297099
TIKTOK_CLIENT_KEY=awoxuopqanrqem7k
WX_APP_ID=
ALI_AUTH_KEY=Z5sHe+2e+pD4URaNjo35d+55ONtIIbs3s1126f8u4ZwWKU3/gJi0QVw1l9pdUuJNx1hOZ5gwzwDJOVMMagYvyVSDmVwJ/2Yu+M7UvI8rt2fqf4nI8Ppka5DNZqa2P79cv3e0ARet4ll/y1TT4a6bhg67yZKFok6J5MgfHaEII/STV38P6pE+KPujOYT9tlKYEWQk7pLrpgflBUt221FpsIyOewt9r1wJvPHUKoPCSME7y29ezhvOefxuVUsBPMkuY0XPzoynFpW/bj7R21yi24wG+394e8e3+0jXwxfICBuj/x16m1Q1AA==
MINI_GAME_KEY=mDdSnjVhe4MjRGDdYZkoazIOiNUmiLCOlXPeLY3E3LI=
MINI_GAME_SECRET=fa2ca42f2e085936
