# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yzbd
# JPush Key configuration
JPUSH_KEY=d8ff3e20a9c7e13ba27c8708
JPUSH_PKGNAME=com.yuewan.yzbd
XIAOMI_APPKEY=MI-
XIAOMI_APPID=MI-
MEIZU_APPKEY=MZ-
MEIZU_APPID=MZ-
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw9s298xlcvppnxp
WX_APP_ID=
ALI_AUTH_KEY=ZO1OeP3owQ3ucbFaR3Pea0oMBMpWDBzTHuuLOtEEuXvYhJ7Wm/+NZaY1yUOCK4WsgP639wr6UInDHSKP7sRA8p/MRKtTven97obn6P6JAhdRqTUa/f8d0uj553cxMnnYypPkgZRHzhe/d8LYKjJ/UXEfhmW2S8CSGmOmBhZ6vMti/VJCa/pauXxE+BTznLBxZWetYDeoJub2nBPR810dPLp6eCmqjuC7wCkKr8TA0qoN8DH9QhDMhyTHqAwFOGI9SATg6V9oldi400Vr+CeT1Q1VF/Ae9KYUt0Vd+HeWyQI=
MINI_GAME_KEY=70uUX1IY/BpxdEPZNRlWsEgGILghhJ3RaWAHP3lXdzU=
MINI_GAME_SECRET=02c71f9691e6458e
