# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.zongjing
# JPush Key configuration
JPUSH_KEY=0c907727c3c8b51ff9430c06
JPUSH_PKGNAME=com.yuewan.zongjing
XIAOMI_APPKEY=MI-5981985429418
XIAOMI_APPID=MI-2882303761519854418
MEIZU_APPKEY=MZ-ca67ed6c945649f683bf3f5c27d00683
MEIZU_APPID=MZ-140267
# Third-party Key configuration
BYTEDANCE_APP_ID=211029
TIKTOK_CLIENT_KEY=awik8d5ri4xd12zm
WX_APP_ID=
ALI_AUTH_KEY=Rabb5mgPGQbz2CPLfZx6/3Hi3/1OJe9o3V6vLX4t+0UQPUwwA5Lik5JuMa7caWxEjFg3DfAfQJLOJJC7FoqhPz7v2ot58akBEL+WZI9zgaI5EWRVtsuxrz8a5q1OMeHFq6peN4qxUJuVJrxQv1OUfVLWTXFUEs8b/TV6KxQ08HFQhvFLzo7xO40+Zqj/Zr5gvkr4QsscGNLZSi26Qw7n61eCHaU3Inxq156p9FCLesPIGJgMUTOLu/apx2Onq3moohp7C+7YQharSF1IcrpSm95XL8251HsXu3mRm+3qWOcpKDBJAFLyJw==
MINI_GAME_KEY=Nj/oUL7wffu2sKzvgilOanyxPb4PFRLmBMFffwJ/rYo=
MINI_GAME_SECRET=02e5e0b81bedc642
