# Configuration except applicationId will be written to the AndroidManifest file
# See build-logic/plugins/src/main/kotlin/com/anjiu/yiyuan/ProjectFlavors.kt
applicationId=com.yuewan.yiyuan
# JPush Key configuration
JPUSH_KEY=0b705ce8e5d679f2a3818b8b
JPUSH_PKGNAME=com.yuewan.yiyuan
XIAOMI_APPKEY=MI-5171853975944
XIAOMI_APPID=MI-2882303761518539944
MEIZU_APPKEY=MZ-d2b1098d9a2546f09d4d05fa8525734d
MEIZU_APPID=MZ-133139
# Third-party Key configuration
BYTEDANCE_APP_ID=
TIKTOK_CLIENT_KEY=aw58f2hfd2695uhi
WX_APP_ID=wx33692da882d769b9
ALI_AUTH_KEY=kUTB5wKIkP4yzlb3ISvVkuRBs5Fk6u0fZ/ReQ21zVndA/vrpk08VWM2PgbfhaLQUTCWkGuw7NrX08gjcTYsjSXqGDl+sQwi2r4g8NfsSq7wENvAbLuvP0LrPADI1n4x0JjR2QZkPHUJp2Q3akHMt1wT9Y0xvKnvj+f9V/ynxE5FeOqdeBFD8b+bZuTb2JKv9ygqHdvzFIlyGFSC38O8BSnRtnJFjhCZpH+jDnoCDXgHTr7sBaBFFM5v5H+/XS+8F40ni0BFYW6yWrqYOSl3qouSeQ5htDclQvT/fbkYfDs5xpnJCluuMmQ==
MINI_GAME_KEY=DpW+CExzRx8QGjUSCicjLiNQH9qkZgYKO3uTVdEdNsc=
MINI_GAME_SECRET=270a493dd21d79cf
