# ManifestPlaceholders Properties
# API
API_YIYUAN=https://appapi.1yuan.cn/
API_BUFF=https://api.buff.vip/api/
API_H5=https://appapi.1yuan.cn/
API_H5_GD=https://kefu.anjiu.cn/
# KEY
BUGLY_APP_ID=059dd1456c
NIM_KEY=f2857e4970a97da42e7ea3a98392952b
UNICORN_KEY=235ed698234f2f4b80e3d50545304def
# File
NETWORK_CONFIG_FILE=@xml/network_security_config