# ManifestPlaceholders Properties
# API
API_YIYUAN=https://sitappapi.1yuan.cn/
API_BUFF=https://sitapi.buff.vip/api/
API_H5=https://sitshare.1yuan.cn/
API_H5_GD=https://sitgm.youxifan.com/
# KEY
BUGLY_APP_ID=bee065d5d8
NIM_KEY=50f420b5c31e55ca995a5f5f748c660e
UNICORN_KEY=235ed698234f2f4b80e3d50545304def
# File
NETWORK_CONFIG_FILE=@xml/network_security_config_debug